plugins:
  - "stylelint-order"
ignoreFiles:
  - "node_modules/**/*"
extends:
  - "stylelint-config-recommended"
  - "stylelint-rscss/config"
rules:
  "order/properties-order":
    - "content"
    - "display"
    - "flex-direction"
    - "flex-wrap"
    - "flex-flow"
    - "justify-content"
    - "align-items"
    - "align-content"
    - "align-self"
    - "flex-grow"
    - "flex-shrink"
    - "flex-basis"
    - "flex"
    - "order"
    - "grid"
    - "grid-area"
    - "grid-auto-columns"
    - "grid-auto-flow"
    - "grid-auto-rows"
    - "grid-column"
    - "grid-column-start"
    - "grid-column-end"
    - "grid-row"
    - "grid-row-start"
    - "grid-row-end"
    - "grid-template"
    - "grid-template-areas"
    - "grid-template-columns"
    - "grid-template-rows"
    - "overflow"
    - "overflow-x"
    - "overflow-y"
    - "visibility"
    - "cursor"
    - "appearance"
    - "object-fit"
    - "float"
    - "clear"
    - "position"
    - "z-index"
    - "top"
    - "right"
    - "bottom"
    - "left"
    - "box-sizing"
    - "list-style"
    - "list-style-type"
    - "list-style-image"
    - "list-style-position"
    - "width"
    - "min-width"
    - "max-width"
    - "height"
    - "min-height"
    - "max-height"
    - "margin"
    - "margin-top"
    - "margin-right"
    - "margin-bottom"
    - "margin-left"
    - "padding"
    - "padding-top"
    - "padding-right"
    - "padding-bottom"
    - "padding-left"
    - "background"
    - "background-attachment"
    - "background-color"
    - "background-image"
    - "background-position"
    - "background-size"
    - "background-repeat"
    - "border"
    - "border-color"
    - "border-style"
    - "border-width"
    - "border-top"
    - "border-right"
    - "border-bottom"
    - "border-left"
    - "border-radius"
    - "border-collapse"
    - "border-spacing"
    - "outline"
    - "outline-width"
    - "outline-style"
    - "outline-offset"
    - "box-shadow"
    - "text-align"
    - "vertical-align"
    - "line-height"
    - "letter-spacing"
    - "text-indent"
    - "white-space"
    - "text-transform"
    - "font"
    - "font-size"
    - "font-family"
    - "font-weight"
    - "text-decoration"
    - "color"
    - "text-shadow"
    - "word-break"
    - "word-wrap"
    - "word-spacing"
    - "opacity"
    - "clip"
    - "transform-origin"
    - "transform"
    - "transition"
    - "animation"
    - "animation-name"
    - "animation-duration"
    - "animation-direction"
    - "animation-delay"
    - "backface-visibility"
    - "-webkit-overflow-scrolling"
    - "-webkit-font-smoothing"
    - "-moz-osx-font-smoothing"
    - "-webkit-tap-highlight-color"
