// Do not modify this file because this file is automatically generated by webpack.
// Note that you shouldn't place css files in pages directory,
//   because next tries to handle generated .d.ts files as page.
const styles: {
  readonly cHeader: string
  readonly options: string
  readonly item: string
  readonly filter: string
  readonly title: string
}
export default styles