// Do not modify this file because this file is automatically generated by webpack.
// Note that you shouldn't place css files in pages directory,
//   because next tries to handle generated .d.ts files as page.
const styles: {
  readonly mainApp: string
  readonly dropping: string
  readonly header: string
  readonly body: string
  readonly footer: string
}
export default styles