// Do not modify this file because this file is automatically generated by webpack.
// Note that you shouldn't place css files in pages directory,
//   because next tries to handle generated .d.ts files as page.
const styles: {
  readonly contentWrapper: string
  readonly header: string
  readonly videos: string
  readonly pageHeader: string
  readonly title: string
  readonly button: string
}
export default styles