// Do not modify this file because this file is automatically generated by webpack.
// Note that you shouldn't place css files in pages directory,
//   because next tries to handle generated .d.ts files as page.
const styles: {
  readonly cVideoList: string
  readonly videosettings: string
  readonly videos: string
  readonly info: string
  readonly videogrid: string
}
export default styles